import type {
  CategoryItem,
  ProdStandDeviceInfo,
} from '@/domain/device/types/common.types';
import type { DeviceInfo } from '@/domain/device/types/device.types';

export interface DeviceContextType {
  deviceState: DeviceInfo;
  deviceStandInfo: ProdStandDeviceInfo;
  deviceCategory: CategoryItem;
}

export const defaultContextValue: DeviceContextType = {
  deviceState: {
    /* ... 기존과 동일 ... */
    admdongCd: '',
    barcode: '',
    buyerMbrSeq: '',
    comType: '',
    dvcAuthCd: '',
    dvcAuthReasonCd: '',
    dvcBrandCd: '',
    dvcModel: '',
    dvcNick: '',
    dvcRegStatCd: '',
    dvcSeq: 0,
    dvcTypeCd: '',
    eUseTp: '',
    gpsLat: '',
    gpsLng: '',
    gpsNationCd: '',
    guideTypeCd: '',
    heartsvcDttm: '',
    instDttm: '',
    instYn: '',
    installAddr: '',
    iotYn: '',
    isGubun: '',
    mbrDvcSeq: 0,
    membershipYn: '',
    netStatus: false,
    ordNo: '',
    pairingDttm: '',
    prodCd: '',
    prodName: '',
    prodNameFull: '',
    prodType: '',
    regDttm: '',
    registUserCount: 0,
    releaseDttm: '',
    resetDttm: '',
    roomPos: '',
    rqDttm: '',
    rq_stat_cd: '',
    salesCntryId: '',
    selfManageYn: '',
    sellTypeCd: '',
    sort: 0,
    stationCd: '',
    unreadYN: '',
    userGradeCd: '',
    userTypeCd: '',
    wifiType: '',
    userGrade: '',
    managerYn: '',
    registAllCount: 0,
    mbrSeq: '',
  },
  deviceStandInfo: {
    familyId: '',
    familyName: '',
    productModel: '',
    productName: [],
    modelCode: '',
    makrModelCode: '',
  },
  deviceCategory: {
    imageUrl: '',
    familyId: '',
    familyName: '',
    productModel: '',
    productName: [],
    modelCode: '',
    makrModelCode: '',
    featureType: '',
    cntryCdAlpha2: '',
    searchRegion: [],
  },
};
